# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mat.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(248, 385)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(248, 385))
        MainWindow.setMaximumSize(QtCore.QSize(248, 385))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 141, 51))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.combobox_actor_choice = QtGui.QComboBox(self.verticalLayoutWidget)
        self.combobox_actor_choice.setFocusPolicy(QtCore.Qt.NoFocus)
        self.combobox_actor_choice.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.combobox_actor_choice.setObjectName(_fromUtf8("combobox_actor_choice"))
        self.combobox_actor_choice.addItem(_fromUtf8(""))
        self.combobox_actor_choice.addItem(_fromUtf8(""))
        self.combobox_actor_choice.addItem(_fromUtf8(""))
        self.combobox_actor_choice.addItem(_fromUtf8(""))
        self.combobox_actor_choice.addItem(_fromUtf8(""))
        self.combobox_actor_choice.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.combobox_actor_choice)
        self.btn_set_actor_choice = QtGui.QPushButton(self.frame)
        self.btn_set_actor_choice.setGeometry(QtCore.QRect(160, 30, 41, 31))
        self.btn_set_actor_choice.setFlat(False)
        self.btn_set_actor_choice.setObjectName(_fromUtf8("btn_set_actor_choice"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(10, 60, 201, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 71, 141, 51))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.combobox_project_choice = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.combobox_project_choice.setFocusPolicy(QtCore.Qt.NoFocus)
        self.combobox_project_choice.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.combobox_project_choice.setObjectName(_fromUtf8("combobox_project_choice"))
        self.combobox_project_choice.addItem(_fromUtf8(""))
        self.combobox_project_choice.addItem(_fromUtf8(""))
        self.combobox_project_choice.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.combobox_project_choice)
        self.btn_set_project_choice = QtGui.QPushButton(self.frame)
        self.btn_set_project_choice.setGeometry(QtCore.QRect(160, 80, 41, 31))
        self.btn_set_project_choice.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_set_project_choice.setFlat(False)
        self.btn_set_project_choice.setObjectName(_fromUtf8("btn_set_project_choice"))
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(10, 110, 201, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 130, 201, 221))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 181, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.btn_createtake = QtGui.QPushButton(self.groupBox)
        self.btn_createtake.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.btn_createtake.setObjectName(_fromUtf8("btn_createtake"))
        self.btn_removetake = QtGui.QPushButton(self.groupBox)
        self.btn_removetake.setGeometry(QtCore.QRect(20, 50, 141, 31))
        self.btn_removetake.setObjectName(_fromUtf8("btn_removetake"))
        self.le_outputfield = QtGui.QLineEdit(self.frame_2)
        self.le_outputfield.setGeometry(QtCore.QRect(10, 190, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        font.setItalic(False)
        self.le_outputfield.setFont(font)
        self.le_outputfield.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.le_outputfield.setReadOnly(True)
        self.le_outputfield.setObjectName(_fromUtf8("le_outputfield"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 181, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btn_savefile = QtGui.QPushButton(self.groupBox_2)
        self.btn_savefile.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.btn_savefile.setObjectName(_fromUtf8("btn_savefile"))
        self.le_filenamefield = QtGui.QLineEdit(self.groupBox_2)
        self.le_filenamefield.setGeometry(QtCore.QRect(10, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        font.setItalic(True)
        self.le_filenamefield.setFont(font)
        self.le_filenamefield.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.le_filenamefield.setReadOnly(False)
        self.le_filenamefield.setProperty("clearButtonEnabled", False)
        self.le_filenamefield.setObjectName(_fromUtf8("le_filenamefield"))
        self.btn_saveas = QtGui.QPushButton(self.groupBox_2)
        self.btn_saveas.setEnabled(True)
        self.btn_saveas.setGeometry(QtCore.QRect(90, 60, 81, 21))
        self.btn_saveas.setObjectName(_fromUtf8("btn_saveas"))
        self.label_tooltitle = QtGui.QLabel(self.frame)
        self.label_tooltitle.setGeometry(QtCore.QRect(10, 10, 141, 16))
        self.label_tooltitle.setObjectName(_fromUtf8("label_tooltitle"))
        self.btn_about_this_tool = QtGui.QPushButton(self.frame)
        self.btn_about_this_tool.setGeometry(QtCore.QRect(160, 10, 41, 20))
        self.btn_about_this_tool.setText(_fromUtf8(""))
        self.btn_about_this_tool.setFlat(False)
        self.btn_about_this_tool.setObjectName(_fromUtf8("btn_about_this_tool"))
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionDocumentation = QtGui.QAction(MainWindow)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionExit_2 = QtGui.QAction(MainWindow)
        self.actionExit_2.setObjectName(_fromUtf8("actionExit_2"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MocapAssistantTool", None))
        self.combobox_actor_choice.setItemText(0, _translate("MainWindow", "-- Select Actor --", None))
        self.combobox_actor_choice.setItemText(1, _translate("MainWindow", "Actor 01", None))
        self.combobox_actor_choice.setItemText(2, _translate("MainWindow", "Actor 02", None))
        self.combobox_actor_choice.setItemText(3, _translate("MainWindow", "Actor 03", None))
        self.combobox_actor_choice.setItemText(4, _translate("MainWindow", "Actor 04", None))
        self.combobox_actor_choice.setItemText(5, _translate("MainWindow", "Actor 05", None))
        self.btn_set_actor_choice.setText(_translate("MainWindow", "Set", None))
        self.combobox_project_choice.setItemText(0, _translate("MainWindow", "-- Select Project --", None))
        self.combobox_project_choice.setItemText(1, _translate("MainWindow", "Project 1", None))
        self.combobox_project_choice.setItemText(2, _translate("MainWindow", "Project 2", None))
        self.btn_set_project_choice.setText(_translate("MainWindow", "Set", None))
        self.groupBox.setTitle(_translate("MainWindow", "Entry", None))
        self.btn_createtake.setText(_translate("MainWindow", "Create Take", None))
        self.btn_removetake.setText(_translate("MainWindow", "Remove Take", None))
        self.le_outputfield.setText(_translate("MainWindow", "output", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "File", None))
        self.btn_savefile.setText(_translate("MainWindow", "Save", None))
        self.le_filenamefield.setText(_translate("MainWindow", "insert filename", None))
        self.btn_saveas.setText(_translate("MainWindow", "Save As..", None))
        self.label_tooltitle.setText(_translate("MainWindow", "Mocap Assistant Tool 1.0", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))
        self.actionAbout.setText(_translate("MainWindow", "About..", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit_2.setText(_translate("MainWindow", "Exit", None))

